[template]
cargo_generate_version = ">=0.10.0"
ignore = [".DS_Store", "target", "Cargo.lock", ".git", "README.md"]
exclude = [
    "scripts/postgres.sh",
    "crates/web-server/src/utils/llm_integration.rs",
    "scripts/*.sh",
    "xtask/src/common.rs",
    "xtask/src/postgres.rs",
]
